name: todo_app
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"



dependencies:
  flutter:
    sdk: flutter
  animated_notch_bottom_bar: ^1.0.0



  cupertino_icons: ^1.0.2
#  flutter_slidable: ^0.6.0
  easy_date_timeline: ^1.1.3
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  firebase_core: ^3.4.1
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  cloud_firestore: ^5.4.1
  lottie: ^3.1.2
  animated_custom_dropdown: ^3.1.1
  provider: ^6.1.2
  firebase_auth: ^5.3.0
  flutter_localization: ^0.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/
    - assets/logo/
    -  assets/icons/
    - assets/transelation/


  fonts:
    - family: poppians
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
