// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClKSxWStcgJt3i-oCpmLkJJnI4tHT-E3E',
    appId: '1:418250157244:web:d481f5de776e4968bcf4b9',
    messagingSenderId: '418250157244',
    projectId: 'todo-app-fb4a1',
    authDomain: 'todo-app-fb4a1.firebaseapp.com',
    storageBucket: 'todo-app-fb4a1.appspot.com',
    measurementId: 'G-RLYQCFJZY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAggjndLZidu1YPzaCS6qlbr-c4HR_S8sc',
    appId: '1:418250157244:android:507c3708725fc50bbcf4b9',
    messagingSenderId: '418250157244',
    projectId: 'todo-app-fb4a1',
    storageBucket: 'todo-app-fb4a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUt9wmNKJuRbpfKov4AKbKWAKAoJIHOE',
    appId: '1:418250157244:ios:3ff858c3d2894519bcf4b9',
    messagingSenderId: '418250157244',
    projectId: 'todo-app-fb4a1',
    storageBucket: 'todo-app-fb4a1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUt9wmNKJuRbpfKov4AKbKWAKAoJIHOE',
    appId: '1:418250157244:ios:3ff858c3d2894519bcf4b9',
    messagingSenderId: '418250157244',
    projectId: 'todo-app-fb4a1',
    storageBucket: 'todo-app-fb4a1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClKSxWStcgJt3i-oCpmLkJJnI4tHT-E3E',
    appId: '1:418250157244:web:82fdffed57ffc091bcf4b9',
    messagingSenderId: '418250157244',
    projectId: 'todo-app-fb4a1',
    authDomain: 'todo-app-fb4a1.firebaseapp.com',
    storageBucket: 'todo-app-fb4a1.appspot.com',
    measurementId: 'G-MXH7702PQL',
  );

}